apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jraye-iot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitlab.example.com/root/iotk3d.git'
    path: manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
